build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank account related local API"
  contactDetails:
    name: "Krishna Jadhav - Developer"
    email: "krishnajadhav0807@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345