spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

card:
  message: "Welcome to EazyBank Card related REST APIs"
  contactDetails:
    name: "John Smith"
    email: "john@eazybytes.com"
  onCallSupport:
    - (453) 392-4832
    - (236) 203-0884